#!/bin/bash
# Logger #1

echo $(date)
export LDRAPPLD=ldrapp_VE.ld
echo $(date)
echo "./mm logger_param LOGGER_1 gps_param GPS_1 CAN_UNIT_E"
./mm logger_param LOGGER_1 gps_param GPS_1 CAN_UNIT_E
cd ..
make flash
