#!/bin/bash
# 09/08/2016
# Compile and load database parameter tables
#
#             1             2             3            4            5   
# ./mm # SHEAVE_1UP encoder_hi_param SHEAVE_1LO encoder_lo_param CANID_UNIT_1E
#
# 
# Makefile source name
export SRCNAME=$2

echo
echo "########## First table db-select: $1 source file: $2 "
make -f Makefile clean
export SRCNAME=$2
make -f Makefile TSELECT=-D$1 && make -f Makefile TSELECT=-D$1 flash

echo
echo "########## Second table db-select: $3 source file: $4"
make -f Makefile clean
export SRCNAME=$4
make -f Makefile TSELECT=-D$3 && make -f Makefile TSELECT=-D$3 flash

echo
echo "########## Table with function command CAN ids: db-select: $5 source file: unit_cmd_canid "
make -f Makefile clean
export SRCNAME=unit_cmd_canid
make -f Makefile TSELECT=-D$5 && make -f Makefile TSELECT=-D$5 flash


