#!/bin/bash
# db_create
# 09/05/2016
# 02/21/2017 path revised for github repo
# Generate 'ij' script and execute
rm x
echo "connect 'jdbc:derby://localhost:1527/$HOME/GliderWinchCommons/embed/svn_common/trunk/db/pcc;create = true';" > x
echo
echo "NOTE: patience--THIS WILL TAKE A WHILE!"
echo
ij x

exit
