#!/bin/bash
# 06/18/2018
# Compile and load database parameter tables
#
#             1             2             3         4
# ./mm # PWRBOX    pwrbox_param   CANID_UNIT_1F  unit_cmd_canid
#
# 
# Makefile source name
export LDRAPPLD=ldrapp_V8.ld

echo
echo "########## First table db-select: $1 source file: $2 "
echo "Loader: $LDRAPPLD"
export SRCNAME=$2
make -f Makefile clean
make -f Makefile TSELECT=-D$1 && make -f Makefile TSELECT=-D$1 flash

echo
echo "########## Table with function command CAN ids: db-select: $4 source file: unit_cmd_canid "
echo "Loader: $LDRAPPLD"
export SRCNAME=unit_cmd_canid
make -f Makefile clean
make -f Makefile TSELECT=-D$3 && make -f Makefile TSELECT=-D$3 flash


