#!/bin/bash
# Supply function instance name for selection of database parameters
#  for compiling and flashing in high address flash
# ./mm <function instance name> <.c file for parameter compiling>
./mm PWRBOX1 pwrbox_param CAN_UNIT_1F unit_cmd_canid
exit

