#!/bin/bash
# Supply function instance name for selection of database parameters
#  for compiling and flashing in high address flash
./mm ENG1_MANIFOLD ENG1_RPM ENG_THROTTLE ENG_T1 CAN_UNIT_3
cd ..
make flash
